 version: '3'
 networks:
   default:
     external:
       name: cloudbuild
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     env_file:
       - perf.env
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     env_file:
       - perf.env
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   redis:
     image: bitnami/redis:latest
     container_name: dva-redis
     env_file:
       - perf.env
     volumes:
       - dvaredis:/bitnami
   dva:
     image: akshayubhat/dva-auto:latest
     container_name: webserver
     env_file:
       - perf.env
     environment:
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_Q_GLOBAL_MODEL=1
       - LAUNCH_Q_GLOBAL_RETRIEVER=1
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - LAUNCH_BY_NAME_analyzer_tagger=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_BY_NAME_detector_textbox=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qtrainer=1
       - LAUNCH_Q_qstreamer=1
       - LAUNCH_SCHEDULER=1
     command: bash -c "git reset --hard && git fetch && git checkout --track origin/performance && git pull && sleep 10 && ./start_container.py"
     ports:
       - "80:80"
       - "8888:8888"
     depends_on:
       - db
       - rabbit
       - redis
     volumes:
       - dvadata:/root/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
  dvaredis: